/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/analytics/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requested, completed, cancelled and expired rides and revenue per hour or day */
        get: operations["rideActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security and administrative actions, newest first by default */
        get: operations["search_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List drivers, optionally filtered by verification status */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driverId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending driver application */
        post: operations["reject_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driverId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend a verified driver and force them offline */
        post: operations["suspend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driverId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a driver so they can go online */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ride counts, rates, time to match and revenue for [from, to); drivers by availability now */
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search all rides by status, request time, passenger or driver */
        get: operations["search_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rides/{rideId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A ride with its passenger, status history, offers and AI analysis status */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health, outbox backlog, dead letters, AI circuit and WebSocket sessions of this instance */
        get: operations["system"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system/test-error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a deliberate test error to Sentry (409 ERROR_REPORTING_DISABLED without SENTRY_DSN) */
        post: operations["testError"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search users by role, status and name/email text */
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspend or reactivate a passenger or driver account */
        patch: operations["changeStatus"];
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in; returns an access token and sets the refresh-token cookie */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session and clear the refresh-token cookie
         * @description Requires header X-Requested-With: rideflow
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh-token cookie and issue a new access token
         * @description Requires header X-Requested-With: rideflow
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a passenger or driver account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report the current GPS position (REST fallback for the WebSocket stream) */
        post: operations["reportLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current driver's profile, verification status and vehicle */
        get: operations["me_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/me/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Earnings from rides completed in [from, to), bucketed by hour or day */
        get: operations["earnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/me/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open ride offers for the current driver */
        get: operations["openOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit licence and vehicle for verification */
        post: operations["submitProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/me/vehicle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the active vehicle; only while offline */
        put: operations["replaceVehicle"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available cars near a point (coarsened and anonymous for passengers) */
        get: operations["nearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Go offline; any pending offer is released */
        post: operations["goOffline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Go online at the given position */
        post: operations["goOnline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fares/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route, surge and a signed fare quote per vehicle category */
        post: operations["estimate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Address at a point, or 204 if there is none (for example at sea) */
        get: operations["reverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Road route between two points (straight-line fallback flagged APPROXIMATE) */
        get: operations["route"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place search, biased towards lat/lng when given; call on submit, not per keystroke */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Newest first by default */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip history: rides booked (passenger) or driven (driver) */
        get: operations["history"];
        put?: never;
        /** Book a ride from a fare quote; matching starts asynchronously */
        post: operations["book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's ongoing ride, or 204 if none (used to restore state after reload) */
        get: operations["active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an open offer (first driver to accept wins) */
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/arrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arrived at pickup (requires a fresh location inside the pickup geofence) */
        post: operations["arrive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passenger cancels; a driver before pickup releases the ride for re-dispatch */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete the trip; measures distance from the GPS trail and computes the final fare */
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/en-route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start driving to the pickup */
        post: operations["enRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate the other participant of a completed ride (once per participant) */
        post: operations["rate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline an open offer */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Passenger on board; the trip starts */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status history of the ride */
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rides/{rideId}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver position and ETA snapshot; live updates then arrive over WebSocket */
        get: operations["tracking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{rideId}/ai-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Computed observations, plus the AI analysis once it is ready (status PENDING until then) */
        get: operations["analysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{rideId}/ai-analysis/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Questions asked about this trip, oldest first */
        get: operations["questions"];
        put?: never;
        /** Ask about this trip; answered from the trip's recorded facts only (503 AI_UNAVAILABLE if AI is down) */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{rideId}/ai-analysis/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a FAILED, UNAVAILABLE or abandoned analysis again (asynchronously) */
        post: operations["regenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's profile */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update name and phone */
        patch: operations["update"];
        trace?: never;
    };
    "/api/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change password; signs out all sessions */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Actual: {
            breakdown: components["schemas"]["FareBreakdownResponse"];
            /** Format: int32 */
            distanceMeters: number;
            /** @enum {string} */
            distanceSource: "TRACKED" | "ESTIMATED";
            /** Format: int32 */
            durationSeconds: number;
            fare: components["schemas"]["Money"];
        };
        AdminOverviewResponse: {
            /** Format: double */
            cancellationRate?: number | null;
            /** Format: double */
            completionRate?: number | null;
            /** Format: date-time */
            from: string;
            grossFares: components["schemas"]["Money"];
            /** Format: double */
            medianSecondsToMatch?: number | null;
            platformFees: components["schemas"]["Money"];
            ridesByStatus: {
                [key: string]: number;
            };
            /** Format: int64 */
            ridesRequested: number;
            /** Format: date-time */
            to: string;
            verifiedDrivers: {
                [key: string]: number;
            };
        };
        AdminRideAnalysis: {
            failureCode?: string | null;
            /** @enum {string} */
            status: "PENDING" | "COMPLETED" | "FAILED" | "UNAVAILABLE";
            /** Format: date-time */
            updatedAt: string;
        };
        AdminRideDetailResponse: {
            analysis?: components["schemas"]["AdminRideAnalysis"] | null;
            offers: components["schemas"]["AdminRideOffer"][];
            passenger?: components["schemas"]["AdminRidePassenger"] | null;
            ride: components["schemas"]["RideResponse"];
            timeline: components["schemas"]["RideTimelineEntryResponse"][];
        };
        AdminRideOffer: {
            /** Format: int32 */
            distanceMeters: number;
            /** Format: uuid */
            driverId: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            offeredAt: string;
            /** Format: date-time */
            respondedAt?: string | null;
            /** Format: int32 */
            round: number;
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "REJECTED" | "EXPIRED" | "CANCELLED";
        };
        AdminRidePassenger: {
            email: string;
            fullName: string;
            /** Format: uuid */
            id: string;
        };
        AdminRideSummaryResponse: {
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: uuid */
            driverId?: string | null;
            dropoffAddress: string;
            fare?: components["schemas"]["Money"] | null;
            fareIsFinal: boolean;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            passengerId: string;
            pickupAddress: string;
            /** Format: date-time */
            requestedAt: string;
            /** @enum {string} */
            status: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
            /** @enum {string} */
            vehicleCategory: "ECONOMY" | "COMFORT" | "XL";
        };
        AuditLogResponse: {
            /** @enum {string} */
            action: "LOGIN_FAILED" | "PASSWORD_CHANGED" | "REFRESH_TOKEN_REUSE_DETECTED" | "DRIVER_PROFILE_SUBMITTED" | "DRIVER_VERIFIED" | "DRIVER_REJECTED" | "DRIVER_SUSPENDED" | "DRIVER_VEHICLE_REPLACED" | "USER_STATUS_CHANGED" | "ADMIN_BOOTSTRAPPED";
            /** Format: uuid */
            actorUserId?: string | null;
            /** Format: date-time */
            createdAt: string;
            details?: {
                [key: string]: unknown;
            } | null;
            /** Format: uuid */
            entityId?: string | null;
            entityType: string;
            /** Format: int64 */
            id: number;
        };
        AuthResponse: {
            accessToken: string;
            /** Format: int64 */
            expiresIn: number;
            tokenType: string;
            user: components["schemas"]["UserResponse"];
        };
        BookRideRequest: {
            dropoff: components["schemas"]["PlaceRequest"];
            /** @enum {string} */
            paymentMethod: "CASH" | "CARD";
            pickup: components["schemas"]["PlaceRequest"];
            quoteId: string;
        };
        CancelRideRequest: {
            reason?: string | null;
        };
        Cancellation: {
            /** @enum {string} */
            cancelledBy: "PASSENGER" | "DRIVER" | "SYSTEM" | "ADMIN";
            reason?: string | null;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        DriverDecisionRequest: {
            reason: string;
        };
        DriverInfo: {
            fullName: string;
            /** Format: uuid */
            id: string;
            ratingAvg?: number | null;
            /** Format: int32 */
            ratingCount: number;
            vehicle?: components["schemas"]["Vehicle"] | null;
        };
        DriverLocation: {
            /** Format: int32 */
            headingDeg?: number | null;
            point: components["schemas"]["GeoPoint"];
            /** Format: date-time */
            recordedAt: string;
        };
        DriverProfileRequest: {
            licenseNumber: string;
            vehicle: components["schemas"]["VehicleRequest"];
        };
        DriverResponse: {
            /** @enum {string} */
            availability: "OFFLINE" | "AVAILABLE" | "ON_TRIP";
            /** Format: date-time */
            createdAt: string;
            email: string;
            fullName: string;
            /** Format: uuid */
            id: string;
            licenseNumber: string;
            ratingAvg?: number | null;
            /** Format: int32 */
            ratingCount: number;
            rejectionReason?: string | null;
            vehicle?: components["schemas"]["VehicleResponse"] | null;
            /** @enum {string} */
            verificationStatus: "PENDING" | "VERIFIED" | "REJECTED" | "SUSPENDED";
            /** Format: date-time */
            verifiedAt?: string | null;
        };
        EarningsBucket: {
            earnings: components["schemas"]["Money"];
            /** Format: date-time */
            start: string;
            /** Format: int32 */
            trips: number;
        };
        EarningsResponse: {
            /** Format: date-time */
            from: string;
            /** @enum {string} */
            granularity: "HOUR" | "DAY";
            series: components["schemas"]["EarningsBucket"][];
            timeZone: string;
            /** Format: date-time */
            to: string;
            total: components["schemas"]["Money"];
            /** Format: int32 */
            tripCount: number;
        };
        Estimate: {
            breakdown?: components["schemas"]["FareBreakdownResponse"] | null;
            /** Format: int32 */
            distanceMeters: number;
            /** Format: int32 */
            durationSeconds: number;
            fare?: components["schemas"]["Money"] | null;
            /** @enum {string} */
            source: "ROUTED" | "APPROXIMATE";
        };
        EtaResponse: {
            /** Format: date-time */
            computedAt: string;
            /** Format: int32 */
            distanceMeters: number;
            /** Format: int32 */
            seconds: number;
            /** @enum {string} */
            source: "ROUTED" | "APPROXIMATE";
            /** @enum {string} */
            target: "PICKUP" | "DROPOFF";
        };
        FareBreakdownResponse: {
            baseFare: string;
            bookingFee: string;
            currency: string;
            distanceCharge: string;
            /** Format: int32 */
            distanceMeters: number;
            /** Format: int32 */
            durationSeconds: number;
            minimumFare: string;
            minimumFareApplied: boolean;
            pricingVersion: string;
            subtotal: string;
            surgeMultiplier: string;
            timeCharge: string;
            total: string;
        };
        FareEstimateRequest: {
            dropoff: components["schemas"]["GeoPoint"];
            pickup: components["schemas"]["GeoPoint"];
        };
        FareEstimateResponse: {
            /** Format: int32 */
            distanceMeters: number;
            /** Format: int32 */
            durationSeconds: number;
            /** @enum {string} */
            estimateSource: "ROUTED" | "APPROXIMATE";
            quotes: components["schemas"]["FareQuoteResponse"][];
            route: components["schemas"]["GeoPoint"][];
            surgeMultiplier: string;
        };
        FareQuoteResponse: {
            breakdown: components["schemas"]["FareBreakdownResponse"];
            estimatedFare: components["schemas"]["Money"];
            /** Format: date-time */
            expiresAt: string;
            minimumFare: components["schemas"]["Money"];
            quoteId: string;
            /** @enum {string} */
            vehicleCategory: "ECONOMY" | "COMFORT" | "XL";
        };
        GeoPoint: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        GoOnlineRequest: {
            location: components["schemas"]["GeoPoint"];
        };
        LocationUpdateRequest: {
            /** Format: double */
            accuracyMeters?: number | null;
            /** Format: int32 */
            headingDeg?: number | null;
            location: components["schemas"]["GeoPoint"];
            /** Format: date-time */
            recordedAt: string;
            /** Format: double */
            speedMps?: number | null;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        Matching: {
            /** Format: int32 */
            radiusMeters: number;
            /** Format: int32 */
            round: number;
        };
        Money: {
            amount: string;
            currency: string;
        };
        NearbyDriverResponse: {
            /** @enum {string} */
            category: "ECONOMY" | "COMFORT" | "XL";
            /** Format: double */
            distanceMeters?: number | null;
            /** Format: uuid */
            driverId?: string | null;
            position: components["schemas"]["GeoPoint"];
        };
        NotificationResponse: {
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            read: boolean;
            /** Format: uuid */
            rideId?: string | null;
            title: string;
            /** @enum {string} */
            type: "DRIVER_ACCEPTED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "DRIVER_REASSIGNING" | "TRIP_STARTED" | "TRIP_COMPLETED" | "RIDE_CANCELLED" | "RIDE_EXPIRED" | "PAYMENT_RECEIVED" | "EARNINGS_RECORDED" | "DRIVER_VERIFIED" | "DRIVER_REJECTED";
        };
        Observation: {
            text: string;
            /** @enum {string} */
            type: "FARE" | "ROUTE" | "TIME" | "COMPARISON" | "OTHER";
        };
        PageResponseAdminRideSummaryResponse: {
            content: components["schemas"]["AdminRideSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            sort: string;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseAuditLogResponse: {
            content: components["schemas"]["AuditLogResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            sort: string;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseDriverResponse: {
            content: components["schemas"]["DriverResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            sort: string;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseNotificationResponse: {
            content: components["schemas"]["NotificationResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            sort: string;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseRideSummaryResponse: {
            content: components["schemas"]["RideSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            sort: string;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseUserResponse: {
            content: components["schemas"]["UserResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            sort: string;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PassengerInfo: {
            fullName: string;
            /** Format: uuid */
            id: string;
        };
        PaymentInfo: {
            amount: components["schemas"]["Money"];
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            method: "CASH" | "CARD";
            /** @enum {string} */
            provider: "CASH" | "SANDBOX";
            /** @enum {string} */
            status: "PENDING" | "CAPTURED" | "FAILED" | "REFUNDED";
        };
        PlaceRequest: {
            address: string;
            point: components["schemas"]["GeoPoint"];
        };
        PlaceResponse: {
            address: string;
            name: string;
            point: components["schemas"]["GeoPoint"];
        };
        RateRideRequest: {
            comment?: string | null;
            /** Format: int32 */
            score: number;
        };
        RatingResponse: {
            comment?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            rideId: string;
            /** Format: int32 */
            score: number;
        };
        RegisterRequest: {
            /** @enum {string} */
            accountType: "PASSENGER" | "DRIVER";
            /** Format: email */
            email: string;
            fullName: string;
            password: string;
            phone?: string | null;
        };
        RideActivityBucket: {
            /** Format: int32 */
            cancelled: number;
            /** Format: int32 */
            completed: number;
            /** Format: int32 */
            expired: number;
            /** Format: int32 */
            requested: number;
            revenue: components["schemas"]["Money"];
            /** Format: date-time */
            start: string;
        };
        RideActivityResponse: {
            /** Format: date-time */
            from: string;
            /** @enum {string} */
            granularity: "HOUR" | "DAY";
            series: components["schemas"]["RideActivityBucket"][];
            timeZone: string;
            /** Format: date-time */
            to: string;
        };
        RideOfferResponse: {
            /** Format: int32 */
            distanceToPickupMeters: number;
            dropoff: components["schemas"]["RidePlace"];
            /** Format: int32 */
            estimatedDistanceMeters: number;
            /** Format: int32 */
            estimatedDurationSeconds: number;
            estimatedFare?: components["schemas"]["Money"] | null;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            offerId: string;
            pickup: components["schemas"]["RidePlace"];
            /** Format: uuid */
            rideId: string;
            /** Format: int32 */
            round: number;
            /** @enum {string} */
            vehicleCategory: "ECONOMY" | "COMFORT" | "XL";
        };
        RidePlace: {
            address: string;
            point: components["schemas"]["GeoPoint"];
        };
        RideResponse: {
            actual?: components["schemas"]["Actual"] | null;
            cancellation?: components["schemas"]["Cancellation"] | null;
            driver?: components["schemas"]["DriverInfo"] | null;
            dropoff: components["schemas"]["RidePlace"];
            estimate: components["schemas"]["Estimate"];
            /** Format: uuid */
            id: string;
            matching: components["schemas"]["Matching"];
            passenger?: components["schemas"]["PassengerInfo"] | null;
            payment?: components["schemas"]["PaymentInfo"] | null;
            /** @enum {string} */
            paymentMethod: "CASH" | "CARD";
            pickup: components["schemas"]["RidePlace"];
            /** @enum {string} */
            status: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
            timestamps: components["schemas"]["Timestamps"];
            /** @enum {string} */
            vehicleCategory: "ECONOMY" | "COMFORT" | "XL";
            /** Format: int64 */
            version: number;
        };
        RideSummaryResponse: {
            /** Format: date-time */
            completedAt?: string | null;
            dropoffAddress: string;
            fare?: components["schemas"]["Money"] | null;
            fareIsFinal: boolean;
            /** Format: uuid */
            id: string;
            pickupAddress: string;
            /** Format: date-time */
            requestedAt: string;
            /** @enum {string} */
            status: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
            /** @enum {string} */
            vehicleCategory: "ECONOMY" | "COMFORT" | "XL";
        };
        RideTimelineEntryResponse: {
            /** @enum {string} */
            actor: "PASSENGER" | "DRIVER" | "SYSTEM" | "ADMIN";
            /** @enum {string|null} */
            from?: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED" | null;
            /** Format: date-time */
            occurredAt: string;
            reason?: string | null;
            /** Format: int64 */
            rideVersion: number;
            /** @enum {string} */
            to: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
        };
        RideTrackingResponse: {
            driverLocation?: components["schemas"]["DriverLocation"] | null;
            eta?: components["schemas"]["EtaResponse"] | null;
            /** Format: uuid */
            rideId: string;
            stale: boolean;
            /** @enum {string} */
            status: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
        };
        RouteResponse: {
            /** Format: int32 */
            distanceMeters: number;
            /** Format: int32 */
            durationSeconds: number;
            path: components["schemas"]["GeoPoint"][];
            /** @enum {string} */
            source: "ROUTED" | "APPROXIMATE";
        };
        SystemStatusResponse: {
            /** Format: int64 */
            aiCallsActive?: number | null;
            aiCircuitOpen?: boolean | null;
            components: {
                [key: string]: string;
            };
            deadLettersByTopic: {
                [key: string]: number;
            };
            errorReporting: boolean;
            health: string;
            /** Format: int64 */
            outboxPending?: number | null;
            redisAvailable?: boolean | null;
            /** Format: int64 */
            webSocketSessions?: number | null;
        };
        TestErrorResponse: {
            eventId: string;
        };
        Timestamps: {
            /** Format: date-time */
            acceptedAt?: string | null;
            /** Format: date-time */
            arrivedAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            enRouteAt?: string | null;
            /** Format: date-time */
            expiredAt?: string | null;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            startedAt?: string | null;
        };
        TripAnalysisResponse: {
            /** @enum {string|null} */
            failureCode?: "TIMEOUT" | "PROVIDER_ERROR" | "RATE_LIMITED" | "INVALID_RESPONSE" | "REFUSED" | "BUSY" | "UNAVAILABLE" | null;
            insights?: components["schemas"]["TripInsights"] | null;
            model?: string | null;
            observations: components["schemas"]["TripObservationResponse"][];
            promptVersion: string;
            provider?: string | null;
            /** Format: uuid */
            rideId: string;
            /** @enum {string} */
            status: "PENDING" | "COMPLETED" | "FAILED" | "UNAVAILABLE";
            /** Format: date-time */
            updatedAt?: string | null;
        };
        TripInsights: {
            comparison?: string | null;
            factKeysUsed: string[];
            fareExplanation: string;
            observations: components["schemas"]["Observation"][];
            recommendations: string[];
            summary: string;
        };
        TripObservationResponse: {
            key: string;
            text: string;
        };
        TripQuestionRequest: {
            question: string;
        };
        TripQuestionResponse: {
            answer?: string | null;
            answerable?: boolean | null;
            /** Format: date-time */
            askedAt: string;
            factKeysUsed?: string[] | null;
            /** @enum {string|null} */
            failureCode?: "TIMEOUT" | "PROVIDER_ERROR" | "RATE_LIMITED" | "INVALID_RESPONSE" | "REFUSED" | "BUSY" | "UNAVAILABLE" | null;
            /** Format: uuid */
            id: string;
            question: string;
            /** @enum {string} */
            status: "COMPLETED" | "FAILED" | "UNAVAILABLE";
        };
        UpdateProfileRequest: {
            fullName: string;
            phone?: string | null;
        };
        UserResponse: {
            /** Format: date-time */
            createdAt: string;
            email: string;
            fullName: string;
            /** Format: uuid */
            id: string;
            phone?: string | null;
            /** @enum {string} */
            role: "PASSENGER" | "DRIVER" | "ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED";
        };
        UserStatusUpdateRequest: {
            reason: string;
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED";
        };
        Vehicle: {
            /** @enum {string} */
            category: "ECONOMY" | "COMFORT" | "XL";
            color: string;
            make: string;
            model: string;
            plateNumber: string;
        };
        VehicleRequest: {
            /** @enum {string} */
            category: "ECONOMY" | "COMFORT" | "XL";
            color: string;
            make: string;
            model: string;
            /** Format: int32 */
            modelYear: number;
            plateNumber: string;
            /** Format: int32 */
            seats: number;
        };
        VehicleResponse: {
            /** @enum {string} */
            category: "ECONOMY" | "COMFORT" | "XL";
            color: string;
            /** Format: uuid */
            id: string;
            make: string;
            model: string;
            /** Format: int32 */
            modelYear: number;
            plateNumber: string;
            /** Format: int32 */
            seats: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rideActivity: {
        parameters: {
            query: {
                from: string;
                to: string;
                granularity?: "HOUR" | "DAY";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideActivityResponse"];
                };
            };
        };
    };
    search_3: {
        parameters: {
            query?: {
                action?: "LOGIN_FAILED" | "PASSWORD_CHANGED" | "REFRESH_TOKEN_REUSE_DETECTED" | "DRIVER_PROFILE_SUBMITTED" | "DRIVER_VERIFIED" | "DRIVER_REJECTED" | "DRIVER_SUSPENDED" | "DRIVER_VEHICLE_REPLACED" | "USER_STATUS_CHANGED" | "ADMIN_BOOTSTRAPPED";
                entityType?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAuditLogResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                verificationStatus?: "PENDING" | "VERIFIED" | "REJECTED" | "SUSPENDED";
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseDriverResponse"];
                };
            };
        };
    };
    reject_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverDecisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    suspend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverDecisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminOverviewResponse"];
                };
            };
        };
    };
    search_2: {
        parameters: {
            query?: {
                status?: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
                from?: string;
                to?: string;
                passengerId?: string;
                driverId?: string;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminRideSummaryResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminRideDetailResponse"];
                };
            };
        };
    };
    system: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    testError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Handed to Sentry; search for the event id there */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TestErrorResponse"];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                role?: "PASSENGER" | "DRIVER" | "ADMIN";
                status?: "ACTIVE" | "SUSPENDED";
                q?: string;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseUserResponse"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    reportLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdateRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    earnings: {
        parameters: {
            query: {
                from: string;
                to: string;
                granularity?: "HOUR" | "DAY";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EarningsResponse"];
                };
            };
        };
    };
    openOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideOfferResponse"][];
                };
            };
        };
    };
    submitProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverProfileRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    replaceVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    nearby: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                radiusMeters?: number;
                category?: "ECONOMY" | "COMFORT" | "XL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NearbyDriverResponse"][];
                };
            };
        };
    };
    goOffline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    goOnline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoOnlineRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DriverResponse"];
                };
            };
        };
    };
    estimate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FareEstimateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FareEstimateResponse"];
                };
            };
        };
    };
    reverse: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"];
                };
            };
            /** @description No address at this point */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"];
                };
            };
        };
    };
    route: {
        parameters: {
            query: {
                fromLat: number;
                fromLng: number;
                toLat: number;
                toLng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RouteResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                lat?: number;
                lng?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlaceResponse"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                unreadOnly?: boolean;
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseNotificationResponse"];
                };
            };
        };
    };
    markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    history: {
        parameters: {
            query?: {
                status?: "REQUESTED" | "MATCHING" | "DRIVER_ASSIGNED" | "DRIVER_ARRIVING" | "DRIVER_ARRIVED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "EXPIRED";
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseRideSummaryResponse"];
                };
            };
        };
    };
    book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookRideRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ongoing ride */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
            /** @description No ongoing ride */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    arrive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelRideRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    enRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    rate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateRideRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RatingResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideResponse"];
                };
            };
        };
    };
    timeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideTimelineEntryResponse"][];
                };
            };
        };
    };
    tracking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RideTrackingResponse"];
                };
            };
        };
    };
    analysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TripAnalysisResponse"];
                };
            };
        };
    };
    questions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TripQuestionResponse"][];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TripQuestionResponse"];
                };
            };
        };
    };
    regenerate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TripAnalysisResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
