package com.rideflow.exception;

import org.springframework.http.HttpStatus;

/**
 * Stable, machine-readable error codes returned in {@link ApiError#code()}. Clients branch on these,
 * never on messages, so existing values must not be renamed.
 */
public enum ErrorCode {

    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    MALFORMED_REQUEST(HttpStatus.BAD_REQUEST),
    INVALID_SORT_FIELD(HttpStatus.BAD_REQUEST),

    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    SESSION_REVOKED(HttpStatus.UNAUTHORIZED),

    FORBIDDEN(HttpStatus.FORBIDDEN),
    ACCOUNT_SUSPENDED(HttpStatus.FORBIDDEN),
    CSRF_HEADER_MISSING(HttpStatus.FORBIDDEN),
    DRIVER_NOT_VERIFIED(HttpStatus.FORBIDDEN),

    NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    DRIVER_PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND),
    RIDE_NOT_FOUND(HttpStatus.NOT_FOUND),

    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    UNSUPPORTED_MEDIA_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE),

    CONFLICT(HttpStatus.CONFLICT),
    CONCURRENT_MODIFICATION(HttpStatus.CONFLICT),
    EMAIL_TAKEN(HttpStatus.CONFLICT),
    PHONE_TAKEN(HttpStatus.CONFLICT),
    LICENSE_TAKEN(HttpStatus.CONFLICT),
    PLATE_TAKEN(HttpStatus.CONFLICT),
    DRIVER_PROFILE_EXISTS(HttpStatus.CONFLICT),
    INVALID_DRIVER_STATE(HttpStatus.CONFLICT),
    INVALID_USER_STATE(HttpStatus.CONFLICT),
    NO_ACTIVE_VEHICLE(HttpStatus.CONFLICT),
    DRIVER_OFFLINE(HttpStatus.CONFLICT),
    DRIVER_ON_TRIP(HttpStatus.CONFLICT),
    DRIVER_UNAVAILABLE(HttpStatus.CONFLICT),
    RIDE_INVALID_TRANSITION(HttpStatus.CONFLICT),
    RIDE_ALREADY_ASSIGNED(HttpStatus.CONFLICT),
    ACTIVE_RIDE_EXISTS(HttpStatus.CONFLICT),
    OFFER_EXPIRED(HttpStatus.CONFLICT),
    NO_SHOW_WAIT_NOT_ELAPSED(HttpStatus.CONFLICT),
    TRACKING_UNAVAILABLE(HttpStatus.CONFLICT),

    WRONG_CURRENT_PASSWORD(HttpStatus.UNPROCESSABLE_CONTENT),
    INVALID_MODEL_YEAR(HttpStatus.UNPROCESSABLE_CONTENT),
    OUTSIDE_SERVICE_AREA(HttpStatus.UNPROCESSABLE_CONTENT),
    PICKUP_EQUALS_DROPOFF(HttpStatus.UNPROCESSABLE_CONTENT),
    QUOTE_INVALID(HttpStatus.UNPROCESSABLE_CONTENT),
    QUOTE_EXPIRED(HttpStatus.UNPROCESSABLE_CONTENT),
    QUOTE_MISMATCH(HttpStatus.UNPROCESSABLE_CONTENT),
    NOT_AT_PICKUP(HttpStatus.UNPROCESSABLE_CONTENT),
    LOCATION_UNAVAILABLE(HttpStatus.UNPROCESSABLE_CONTENT),
    STALE_LOCATION(HttpStatus.UNPROCESSABLE_CONTENT),

    RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),

    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    GEOCODING_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
