package com.rideflow.entity;

public enum AuditAction {
    LOGIN_FAILED,
    PASSWORD_CHANGED,
    REFRESH_TOKEN_REUSE_DETECTED,
    DRIVER_PROFILE_SUBMITTED,
    DRIVER_VERIFIED,
    DRIVER_REJECTED,
    DRIVER_SUSPENDED,
    USER_STATUS_CHANGED,
    ADMIN_BOOTSTRAPPED
}
