package com.rideflow.entity;

import com.rideflow.exception.ErrorCode;
import com.rideflow.exception.InvalidStateException;
import com.rideflow.geospatial.GeoPoint;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * The ride aggregate. Status only changes through the intention-revealing methods below, each of which
 * is validated by {@link RideStateMachine}. The geography columns in the table are generated by
 * PostGIS from the lat/lng mapped here.
 */
@Entity
@Table(name = "rides")
public class Ride extends TimestampedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "passenger_id", nullable = false, updatable = false)
    private UUID passengerId;

    @Column(name = "driver_id")
    private UUID driverId;

    @Column(name = "vehicle_id")
    private UUID vehicleId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private RideStatus status;

    @Enumerated(EnumType.STRING)
    @Column(name = "vehicle_category", nullable = false, length = 16)
    private VehicleCategory vehicleCategory;

    @Column(name = "pickup_lat", nullable = false)
    private double pickupLat;

    @Column(name = "pickup_lng", nullable = false)
    private double pickupLng;

    @Column(name = "pickup_address", nullable = false)
    private String pickupAddress;

    @Column(name = "dropoff_lat", nullable = false)
    private double dropoffLat;

    @Column(name = "dropoff_lng", nullable = false)
    private double dropoffLng;

    @Column(name = "dropoff_address", nullable = false)
    private String dropoffAddress;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false, length = 16)
    private PaymentMethod paymentMethod;

    @Column(name = "estimated_distance_m", nullable = false)
    private int estimatedDistanceMeters;

    @Column(name = "estimated_duration_s", nullable = false)
    private int estimatedDurationSeconds;

    @Enumerated(EnumType.STRING)
    @Column(name = "estimate_source", nullable = false, length = 16)
    private EstimateSource estimateSource;

    /** Locked at quote time so the passenger pays the surge they were shown. */
    @Column(name = "surge_multiplier", nullable = false, precision = 4, scale = 2)
    private BigDecimal surgeMultiplier;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    @Column(name = "actual_distance_m")
    private Integer actualDistanceMeters;

    @Column(name = "actual_duration_s")
    private Integer actualDurationSeconds;

    @Enumerated(EnumType.STRING)
    @Column(name = "distance_source", length = 16)
    private DistanceSource distanceSource;

    @Column(name = "matching_round", nullable = false)
    private short matchingRound;

    @Column(name = "matching_radius_m", nullable = false)
    private int matchingRadiusMeters;

    @Column(name = "round_started_at")
    private Instant roundStartedAt;

    @Column(name = "requested_at", nullable = false, updatable = false)
    private Instant requestedAt;

    @Column(name = "accepted_at")
    private Instant acceptedAt;

    @Column(name = "en_route_at")
    private Instant enRouteAt;

    @Column(name = "arrived_at")
    private Instant arrivedAt;

    @Column(name = "started_at")
    private Instant startedAt;

    @Column(name = "completed_at")
    private Instant completedAt;

    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    @Column(name = "expired_at")
    private Instant expiredAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "cancelled_by", length = 16)
    private ActorType cancelledBy;

    @Column(name = "cancellation_reason")
    private String cancellationReason;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    protected Ride() {
    }

    /** Everything fixed at request time, taken from the validated fare quote. */
    public record RequestDetails(
            UUID passengerId,
            VehicleCategory category,
            GeoPoint pickup,
            String pickupAddress,
            GeoPoint dropoff,
            String dropoffAddress,
            PaymentMethod paymentMethod,
            int estimatedDistanceMeters,
            int estimatedDurationSeconds,
            EstimateSource estimateSource,
            BigDecimal surgeMultiplier,
            String currency) {
    }

    /** A status change that just happened, for the status history and domain events. */
    public record StatusChange(RideStatus from, RideStatus to) {
    }

    public static Ride request(RequestDetails details, Instant now) {
        Ride ride = new Ride();
        ride.passengerId = details.passengerId();
        ride.vehicleCategory = details.category();
        ride.pickupLat = details.pickup().lat();
        ride.pickupLng = details.pickup().lng();
        ride.pickupAddress = details.pickupAddress();
        ride.dropoffLat = details.dropoff().lat();
        ride.dropoffLng = details.dropoff().lng();
        ride.dropoffAddress = details.dropoffAddress();
        ride.paymentMethod = details.paymentMethod();
        ride.estimatedDistanceMeters = details.estimatedDistanceMeters();
        ride.estimatedDurationSeconds = details.estimatedDurationSeconds();
        ride.estimateSource = details.estimateSource();
        ride.surgeMultiplier = details.surgeMultiplier();
        ride.currency = details.currency();
        ride.status = RideStatus.REQUESTED;
        ride.requestedAt = now;
        return ride;
    }

    /**
     * Starts matching round {@code round} with the given search radius. The first round also moves the
     * ride from REQUESTED to MATCHING; later rounds keep it in MATCHING.
     *
     * @return the status change, or {@code null} when the ride was already MATCHING
     */
    public StatusChange beginMatchingRound(int round, int radiusMeters, Instant now) {
        StatusChange change = null;
        if (status == RideStatus.REQUESTED) {
            change = moveTo(RideStatus.MATCHING, ActorType.SYSTEM);
        } else if (status != RideStatus.MATCHING) {
            throw new InvalidStateException(ErrorCode.RIDE_INVALID_TRANSITION,
                    "Cannot start a matching round for a ride in status " + status);
        }
        this.matchingRound = (short) round;
        this.matchingRadiusMeters = radiusMeters;
        this.roundStartedAt = now;
        return change;
    }

    public StatusChange assignDriver(UUID driverId, UUID vehicleId, Instant now) {
        StatusChange change = moveTo(RideStatus.DRIVER_ASSIGNED, ActorType.DRIVER);
        this.driverId = driverId;
        this.vehicleId = vehicleId;
        this.acceptedAt = now;
        return change;
    }

    public StatusChange markEnRoute(Instant now) {
        StatusChange change = moveTo(RideStatus.DRIVER_ARRIVING, ActorType.DRIVER);
        this.enRouteAt = now;
        return change;
    }

    public StatusChange markArrived(Instant now) {
        StatusChange change = moveTo(RideStatus.DRIVER_ARRIVED, ActorType.DRIVER);
        this.arrivedAt = now;
        return change;
    }

    public StatusChange start(Instant now) {
        StatusChange change = moveTo(RideStatus.IN_PROGRESS, ActorType.DRIVER);
        this.startedAt = now;
        return change;
    }

    public StatusChange complete(int distanceMeters, DistanceSource source, Instant now) {
        StatusChange change = moveTo(RideStatus.COMPLETED, ActorType.DRIVER);
        this.completedAt = now;
        this.actualDistanceMeters = distanceMeters;
        this.distanceSource = source;
        this.actualDurationSeconds = (int) Duration.between(startedAt, now).toSeconds();
        return change;
    }

    public StatusChange cancel(ActorType actor, String reason, Instant now) {
        StatusChange change = moveTo(RideStatus.CANCELLED, actor);
        this.cancelledAt = now;
        this.cancelledBy = actor;
        this.cancellationReason = reason;
        return change;
    }

    public StatusChange expire(Instant now) {
        StatusChange change = moveTo(RideStatus.EXPIRED, ActorType.SYSTEM);
        this.expiredAt = now;
        return change;
    }

    /** The assigned driver backed out before pickup: detach them and search again from round one. */
    public StatusChange redispatch() {
        StatusChange change = moveTo(RideStatus.MATCHING, ActorType.DRIVER);
        this.driverId = null;
        this.vehicleId = null;
        this.acceptedAt = null;
        this.enRouteAt = null;
        this.matchingRound = 0;
        this.roundStartedAt = null;
        return change;
    }

    private StatusChange moveTo(RideStatus target, ActorType actor) {
        RideStateMachine.requireAllowed(status, target, actor);
        RideStatus previous = status;
        this.status = target;
        return new StatusChange(previous, target);
    }

    public boolean isAssignedTo(UUID candidateDriverId) {
        return driverId != null && driverId.equals(candidateDriverId);
    }

    public GeoPoint getPickup() {
        return new GeoPoint(pickupLat, pickupLng);
    }

    public GeoPoint getDropoff() {
        return new GeoPoint(dropoffLat, dropoffLng);
    }

    public UUID getId() {
        return id;
    }

    public UUID getPassengerId() {
        return passengerId;
    }

    public UUID getDriverId() {
        return driverId;
    }

    public UUID getVehicleId() {
        return vehicleId;
    }

    public RideStatus getStatus() {
        return status;
    }

    public VehicleCategory getVehicleCategory() {
        return vehicleCategory;
    }

    public String getPickupAddress() {
        return pickupAddress;
    }

    public String getDropoffAddress() {
        return dropoffAddress;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public int getEstimatedDistanceMeters() {
        return estimatedDistanceMeters;
    }

    public int getEstimatedDurationSeconds() {
        return estimatedDurationSeconds;
    }

    public EstimateSource getEstimateSource() {
        return estimateSource;
    }

    public BigDecimal getSurgeMultiplier() {
        return surgeMultiplier;
    }

    public String getCurrency() {
        return currency;
    }

    public Integer getActualDistanceMeters() {
        return actualDistanceMeters;
    }

    public Integer getActualDurationSeconds() {
        return actualDurationSeconds;
    }

    public DistanceSource getDistanceSource() {
        return distanceSource;
    }

    public int getMatchingRound() {
        return matchingRound;
    }

    public int getMatchingRadiusMeters() {
        return matchingRadiusMeters;
    }

    public Instant getRoundStartedAt() {
        return roundStartedAt;
    }

    public Instant getRequestedAt() {
        return requestedAt;
    }

    public Instant getAcceptedAt() {
        return acceptedAt;
    }

    public Instant getEnRouteAt() {
        return enRouteAt;
    }

    public Instant getArrivedAt() {
        return arrivedAt;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public Instant getCancelledAt() {
        return cancelledAt;
    }

    public Instant getExpiredAt() {
        return expiredAt;
    }

    public ActorType getCancelledBy() {
        return cancelledBy;
    }

    public String getCancellationReason() {
        return cancellationReason;
    }

    public long getVersion() {
        return version;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        return other instanceof Ride ride && id != null && id.equals(ride.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(Ride.class);
    }
}
