/** Every TanStack Query key in one place, so invalidation after mutations and pushes stays consistent. */
export const queryKeys = {
  me: ["me"] as const,
  activeRide: ["rides", "active"] as const,
  ride: (rideId: string) => ["rides", rideId] as const,
  rideTimeline: (rideId: string) => ["rides", rideId, "timeline"] as const,
  tracking: (rideId: string) => ["rides", rideId, "tracking"] as const,
  rideMessages: (rideId: string) => ["rides", rideId, "messages"] as const,
  rideHistory: (page: number, status: string) => ["rides", "history", page, status] as const,
  estimate: (key: string) => ["fares", "estimate", key] as const,
  nearby: (lat: number, lng: number, radiusMeters: number) => ["drivers", "nearby", lat, lng, radiusMeters] as const,
  route: (key: string) => ["geo", "route", key] as const,
  analysis: (rideId: string) => ["trips", rideId, "analysis"] as const,
  questions: (rideId: string) => ["trips", rideId, "questions"] as const,
  driverProfile: ["driver", "me"] as const,
  offers: ["driver", "offers"] as const,
  earnings: (from: string, to: string, granularity: string) => ["driver", "earnings", from, to, granularity] as const,
  notifications: ["notifications"] as const,
  unreadCount: ["notifications", "unread"] as const,
  admin: {
    overview: (from: string, to: string) => ["admin", "overview", from, to] as const,
    activity: (from: string, to: string, granularity: string) => ["admin", "activity", from, to, granularity] as const,
    rides: (filters: string) => ["admin", "rides", filters] as const,
    ride: (rideId: string) => ["admin", "rides", "detail", rideId] as const,
    drivers: (filters: string) => ["admin", "drivers", filters] as const,
    users: (filters: string) => ["admin", "users", filters] as const,
    system: ["admin", "system"] as const,
    audit: (filters: string) => ["admin", "audit", filters] as const,
  },
};
